name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      run: |
        sudo apt update
        sudo apt install nodejs npm

    - name: Install pm2 globally
      run: npm install -g pm2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Check SSH Connection
      run: ssh -o "StrictHostKeyChecking=no" ${{ secrets.USERNAME_PROD }}@${{ secrets.HOST_PROD }} -p ${{ secrets.SSH_PORT_PROD }} "echo 'SSH connection successful!'"

    - name: Deploy to AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ${{ secrets.USERNAME_PROD }}
        key: ${{ secrets.SSH_KEY_PROD }}
        port: ${{ secrets.SSH_PORT_PROD }}
        script: |
          cd /home/ubuntu/fuzuki-inu-marketing
          git pull origin main
          npm install
          npm run build
          pm2 restart 0
