name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST_PROD }}
        username: ${{ secrets.AWS_USERNAME_PROD }}
        key: ${{ secrets.AWS_SSH_KEY_PROD }}
        port: ${{ secrets.AWS_SSH_PORT_PROD }}
        script: |
          cd /home/ubuntu/fuzuki-inu-marketing
          git pull origin main
          npm install
          npm run build
          pm2 restart 0
