name: CI/CD Pipeline for React Application

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v18.17.0'  # Adjust this as needed

    - name: Install npm dependencies
      run: npm install -f

    - name: Build the React application
      run: npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/"
        target: "/home/ubuntu/fuzuki-inu-marketing/build"

    - name: Restart PM2 process
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/fuzuki-inu-marketing
          pm2 restart 0
